interface Player {
    id: String
    name: String
    bestPosition: String
    finishing: number
    dribbling: number
    firstTouch: number
    passing: number
    technique: number
    crossing: number
    heading: number
    longShots: number
    marking: number
    tackling: number
    aggression: number
    anticipation: number
    bravery: number
    composure: number
    concentration: number
    decisions: number
    determination: number
    positioning: number
    teamwork: number
    vision: number
    acceleration: number
    agility: number
    balance: number
    jumpingReach: number
    naturalFitness: number
    pace: number
    stamina: number
    strength: number
}